---
title: "WritingExercise05"
---

# Reflect on your own skills and development as a writer

- What are the areas you think you are good at? Where can you improve?
I think I can cover a wide variety of topics, but being concise/timely with my writing can sometimes be an issue, as I get the nagging worry that I am not representing my full train of thought-- so to say, I have too much to say at times, though maybe not all important. Being concise, and editing my work to reflect that goal. 

- How will you further develop your skills over the coming year? Can you make a specific, detailed plan?
Write early, so i can leave time for myself to edit, come back with "fresh eyes" and have a better perspective to edit my writing(s).

# Reflect on writing more generally

- What principles of composition discussed today did you find most useful?
Most were known to me, though I thought it insightful to use active language and to not mistakenly add more words than neccessary due to a lack of positive context or driven thought. 

- If you were going to formulate your own writing rules, what would they be?
Be concise. 
Each paragraph should have a soft landing to read or follow up the previous one succinctly/relatedly. 
Reread aloud to catch any awkward phrases/sentence structures. 

# Commit your reflections to writing

Compose a paragraph summarizing your reflections. Remember to use the "commit" process to save your changes when you are finished.

Writing is a skill that comprises the solidfying and dressing our inner thoughts, motives and goals. I myself have issues pruning and picking which of my thoughts to commit to paper, but am able to do so with diligent editing. One way to actively avoid this behavior is to use an active voice in order to avoid uneccessary words in a statement or description. 
